title: 1+MG Trust Framework
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: 1+MG Trust Framework
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Example of ELIXIR toolkit theme as a remote jekyll theme"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.21.0

exclude:
  - README.md
  - vendor

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
