title: 1+MG Trust Framework
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: "Example of ELIXIR toolkit theme as a remote jekyll theme"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.23.0

sass:
  style: compressed
  sourcemap: never

gtag: 
# Google analytics tag

theme_variables:
  theme_color: da366e
  topnav:
    brand_logo: assets/img/main_logo.svg
  fonts:
    - https://fonts.googleapis.com/css2?family=Fira+Sans&Open+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap
    

exclude:
  - README.md
  - .gitignore

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: trust_framework
      search_exclude: false
  -
    scope:
      path: "pages/contribute"
    values:
      sidebar: contribute
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/data_life_cycle/TEMPLATE_rdm_cycle.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/national_resources/TEMPLATE_resources.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/tool_assembly/TEMPLATE_tool_assembly.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your_domain/TEMPLATE_your_domain.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your_role/TEMPLATE_your_role.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your_tasks/TEMPLATE_your_tasks.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true

  -
    scope:
      path: "pages/data_life_cycle"
    values:
      type: data_life_cycle

  -
    scope:
      path: "pages/data_life_cycle/TEMPLATE_rdm_cycle.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/national_resources/TEMPLATE_resources.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/tool_assembly/TEMPLATE_tool_assembly.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your_domain/TEMPLATE_your_domain.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your_role/TEMPLATE_your_role.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your_tasks/TEMPLATE_your_tasks.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/data_life_cycle"
    values:
      type: data_life_cycle
  -
    scope:
      path: "pages/your_domain"
    values:
      type: your_domain
  -
    scope:
      path: "pages/your_tasks"
    values:
      type: your_tasks
  -
    scope:
      path: "pages/your_role"
    values:
      type: your_role
  -
    scope:
      path: "pages/tool_assembly"
    values:
      type: tool_assembly
  -
    scope:
      path: "pages/national_resources"
    values:
      type: national_resources
      datatable: true
  -
    scope:
      path: "pages/contribute"
    values:
      sidebar: contribute
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
