title: 1+MG Trust Framework
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: 1+MG Trust Framework
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Example of ELIXIR toolkit theme as a remote jekyll theme"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.21.0

sass:
  style: compressed
  sourcemap: never

gtag: 
# Google analytics tag

theme_variables:
  theme_color: da366e
  topnav:
    brand_logo: assets/img/main_logo.svg
  fonts:
    - https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap

exclude:
  - README.md
  - .gitignore

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: trust_framework
      search_exclude: false
  -
    scope:
      path: "pages/contribute"
    values:
      sidebar: contribute
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
